// frontend/src/app/shared/components/input/input.component.ts
import { Component,Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-input',
  standalone: true,
  imports: [InputComponent,CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css'
})
export class InputComponent {
  @Input() id!: string;
  @Input() name!: string;
  @Input() type: string = 'text';
  @Input() label!: string;
  @Input() autocomplete: string = '';
  @Input() required: boolean = false;
  @Input() class: string = '';  // Required attribute
}

<div>
  <label [attr.for]="id" class="block text-sm/6 font-medium text-gray-900">{{ label }}</label>
  <div class="mt-2">
    <input
      [id]="id"
      [name]="name"
      [type]="type"
      [autocomplete]="autocomplete"
      [required]="required"
      [ngClass]="class"
      class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6"
    />
  </div>
</div>

// frontend/src/components/ui/Input.jsx
// src/components/ui/Input.js
export default function Input({ label, ...props}) {
  return (
    <div className="mb-4">
      <label htmlFor={props.id} className="block text-gray-700 mb-2">
        {label}
      </label>
      <input
        {...props}
        className="border border-gray-300 rounded-md p-2 w-full text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500" // Adjust text color here
        placeholder={props.placeholder}
      />
    </div>
  );
}
