// frontend/src/app/shared/components/input/input.component.ts
import { Component,Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-input',
  standalone: true,
  imports: [InputComponent,CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css'
})
export class InputComponent {
  @Input() id!: string;
  @Input() name!: string;
  @Input() type: string = 'text';
  @Input() label!: string;
  @Input() autocomplete: string = '';
  @Input() required: boolean = false;
  @Input() class: string = '';  // Required attribute
}

<div>
  <label [attr.for]="id" class="block text-sm/6 font-medium text-gray-900">{{ label }}</label>
  <div class="mt-2">
    <input
      [id]="id"
      [name]="name"
      [type]="type"
      [autocomplete]="autocomplete"
      [required]="required"
      [ngClass]="class"
      class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6"
    />
  </div>
</div>

// dashboard/src/app/oganizationWebsite/shared/input/input.tsx
import React from 'react';

interface InputProps {
  id: string;
  name: string;
  type: string;
  label: string;
  required?: boolean;
  placeholder?: string;
  autoComplete?: string;
  className?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;  // Add this line
}

const Input: React.FC<InputProps> = ({
  id,
  name,
  type,
  label,
  required = false,
  placeholder = '',
  autoComplete = '',
  className = '',
  value = '',
  onChange, // Make sure to destructure onChange
}) => {
  return (
    <div className={`space-y-2 ${className}`}>
      <label htmlFor={id} className="text-sm font-medium text-gray-900">
        {label}
      </label>
      <input
        id={id}
        name={name}
        type={type}
        value={value}
        required={required}
        placeholder={placeholder}
        autoComplete={autoComplete}
        className="w-full px-4 py-2 text-gray-900 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-600 transition duration-300"
        onChange={onChange} 
      />
    </div>
  );
};

export default Input;
